apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
  labels:
    env: joomlaVolume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
