apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  labels:
    env: mysqlVolume
spec:
  storageClassName: myclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 2Gi