apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
  labels:
    env: mysqlVolume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests: 
      storage: 10Gi